apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: salesx-backend-prod

namespace: salesx-production

commonLabels:
  environment: production

bases:
  - ../../base
  - patches/storage/pv.yaml
  - patches/storage/pvc.yaml

patchesStrategicMerge:
  - patches/django-backend-patch.yaml
  - patches/celery-worker-patch.yaml
  - patches/celery-beat-patch.yaml
  # - patches/redis-patch.yaml
  # - patches/postgresql-patch.yaml

images:
  - name: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx
    newTag: backend-Enhance-LeadModal-and-UnifiedTimeli-02f4db48a00dd07ce90e1879274e03c16ee4a9d9

commonAnnotations:
  kubernetes.io/change-cause: "Updated to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx:backend-Enhance-LeadModal-and-UnifiedTimeli-02f4db48a00dd07ce90e1879274e03c16ee4a9d9"
