apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: salesx-backend-prod

namespace: salesx-production

commonLabels:
  environment: production

bases:
  - ../../base
  - patches/storage/pv.yaml
  - patches/storage/pvc.yaml

patchesStrategicMerge:
  - patches/django-backend-patch.yaml
  - patches/celery-worker-patch.yaml
  - patches/celery-beat-patch.yaml
  # - patches/redis-patch.yaml
  # - patches/postgresql-patch.yaml

images:
  - name: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx
    newTag: backend-Refactor-website-field-type-and-enh-f9bf2edb6ba3b462c60b93e5507fef2f7b47dd9a

commonAnnotations:
  kubernetes.io/change-cause: "Updated to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx:backend-Refactor-website-field-type-and-enh-f9bf2edb6ba3b462c60b93e5507fef2f7b47dd9a"
