apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: salesx-backend-prod

namespace: salesx-production

commonLabels:
  environment: production

bases:
  - ../../base
  - patches/storage/pv.yaml
  - patches/storage/pvc.yaml

patchesStrategicMerge:
  - patches/django-backend-patch.yaml
  - patches/celery-worker-patch.yaml
  - patches/celery-beat-patch.yaml
  # - patches/redis-patch.yaml
  # - patches/postgresql-patch.yaml

images:
  - name: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx
    newTag: backend-Implement-application-launcher-for-59b27c040ed7dda3820384ecd16b5805b3497d59

commonAnnotations:
  kubernetes.io/change-cause: "Updated to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx:backend-Implement-application-launcher-for-59b27c040ed7dda3820384ecd16b5805b3497d59"
