apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: salesx-frontend-base

namespace: salesx-production

commonLabels:
  app: salesx
  managed-by: kustomize

resources:
  # Deployments
  - deployment/frontend-deployment.yaml
  
  # Services
  - services/frontend-service.yaml
  
  # ConfigMaps
  - configmap/nginx-config.yaml
  
  # Secrets
  - secrets/salesx-frontend-secrets.yaml
  
  # Autoscaling
  - autoscaling/frontend-hpa.yaml

images:
  - name: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx
    newTag: frontend-latest
