apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: salesx-frontend-prod

namespace: salesx-production

commonLabels:
  environment: production

bases:
  - ../../base

patchesStrategicMerge:
  - patches/frontend-patch.yaml

images:
  - name: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx
    newTag: frontend-Refactor-website-field-type-and-enh-f9bf2edb6ba3b462c60b93e5507fef2f7b47dd9a

commonAnnotations:
  kubernetes.io/change-cause: "Updated to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx:frontend-Refactor-website-field-type-and-enh-f9bf2edb6ba3b462c60b93e5507fef2f7b47dd9a"
