apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: salesx-frontend-prod

namespace: salesx-production

commonLabels:
  environment: production

bases:
  - ../../base

patchesStrategicMerge:
  - patches/frontend-patch.yaml

images:
  - name: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx
    newTag: frontend-Refactor-currency-formatting-and-ba-b8ad1dff8b2444ade206e4b7ad1d7d59252b4387

commonAnnotations:
  kubernetes.io/change-cause: "Updated to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx:frontend-Refactor-currency-formatting-and-ba-b8ad1dff8b2444ade206e4b7ad1d7d59252b4387"
