apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: salesx-frontend-prod

namespace: salesx-production

commonLabels:
  environment: production

bases:
  - ../../base

patchesStrategicMerge:
  - patches/frontend-patch.yaml

images:
  - name: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx
    newTag: frontend-Implement-application-launcher-for-59b27c040ed7dda3820384ecd16b5805b3497d59

commonAnnotations:
  kubernetes.io/change-cause: "Updated to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx:frontend-Implement-application-launcher-for-59b27c040ed7dda3820384ecd16b5805b3497d59"
