apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: salesx-frontend-prod

namespace: salesx-production

commonLabels:
  environment: production

bases:
  - ../../base

patchesStrategicMerge:
  - patches/frontend-patch.yaml

images:
  - name: 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx
    newTag: frontend-Enhance-LeadModal-functionality-and-3906e4ddd80a1b72e12cdb5ab84d2943672cbf17

commonAnnotations:
  kubernetes.io/change-cause: "Updated to 399600302704.dkr.ecr.ap-south-1.amazonaws.com/salesx:frontend-Enhance-LeadModal-functionality-and-3906e4ddd80a1b72e12cdb5ab84d2943672cbf17"
