apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    app: salesx
    component: pgadmin
type: Opaque
stringData:
  pgadmin-email: admin@salesx.com
  pgadmin-password: admin123  # Change this in production
