apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: salesx-backend-secrets
  labels:
    app: salesx-backend-secrets
    component: secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:salesx-backend-prod-G7196u
        objectAlias: ".env"
        objectType: "secretsmanager"
      - objectName: arn:aws:secretsmanager:ap-south-1:399600302704:secret:salesx-firebase-prod-5SGKZL
        objectAlias: "firebase-credentials.json"
        objectType: "secretsmanager"